version: "3.6"
services:
  wallet:
    container_name: "${STAGE}-${APP_NAME}-wallet"
    build: ./wallet
    ports:
      - "8888:8888"
    volumes:
      - ${WALLET_DATA}:/opt/application/data
  postgres:
    container_name: "${STAGE}-${APP_NAME}-postgres"
    image: mdillon/postgis:11
    ports:
      - "5432:5432"
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
      POSTGRES_DB: "${POSTGRES_DB}"
  hapi:
    container_name: "${STAGE}-${APP_NAME}-hapi"
    build: ./hapi
    ports:
      - "9090:9090"
    volumes:
      - ./hapi:/usr/app
    environment:
      SERVER_PORT: "${SERVER_PORT}"
      SERVER_ADDRESS: "${SERVER_ADDRESS}"
      HASURA_URL: "${HASURA_URL}"
      HASURA_ADMIN_SECRET: "${HASURA_ADMIN_SECRET}"
      EOS_API_URL: "${EOS_API_URL}"
      EOS_API_CHAIN_ID: "${EOS_API_CHAIN_ID}"
      EOS_BASE_ACCOUNT: "${EOS_BASE_ACCOUNT}"
      EOS_BASE_ACCOUNT_PASSWORD: "${EOS_BASE_ACCOUNT_PASSWORD}"
      EOS_WALLET_URL: "${EOS_WALLET_URL}"
      JWT_SECRECT: "${JWT_SECRECT}"
      JWT_ISS: "${JWT_ISS}"
      MAIL_HOST: "${MAIL_HOST}"
      MAIL_PORT: "${MAIL_PORT}"
      MAIL_USER: "${MAIL_USER}"
      MAIL_PASSWORD: "${MAIL_PASSWORD}"
      COMMUNITY_ASSET: "${COMMUNITY_ASSET}"
      LIFEBANKCODE_CONTRACTNAME: "${LIFEBANKCODE_CONTRACTNAME}"
      CONSENT2LIFE_CONTRACTNAME: "${CONSENT2LIFE_CONTRACTNAME}"
      LIFEBANKCOIN_CONTRACTNAME: "${LIFEBANKCOIN_CONTRACTNAME}"
  hasura:
    container_name: "${STAGE}-${APP_NAME}-hasura"
    image: hasura/graphql-engine:v1.2.1.cli-migrations-v2
    ports:
      - "8080:8080"
    volumes:
      - ./hasura/migrations:/hasura-migrations
      - ./hasura/metadata:/hasura-metadata
    environment:
      HASURA_GRAPHQL_DATABASE_URL: "${DATABASE_URL}"
      HASURA_GRAPHQL_ENABLE_CONSOLE: "${HASURA_GRAPHQL_ENABLE_CONSOLE}"
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: "${HASURA_GRAPHQL_ENABLED_LOG_TYPES}"
      HASURA_GRAPHQL_ADMIN_SECRET: "${HASURA_GRAPHQL_ADMIN_SECRET}"
      HASURA_GRAPHQL_UNAUTHORIZED_ROLE: "${HASURA_GRAPHQL_UNAUTHORIZED_ROLE}"
      HASURA_GRAPHQL_JWT_SECRET: "${HASURA_GRAPHQL_JWT_SECRET}"
    depends_on:
      - postgres
  webapp:
    container_name: "${STAGE}-${APP_NAME}-webapp"
    build:
      context: ./webapp
      args:
        REACT_APP_EOS_API_HOST: "${REACT_APP_EOS_API_HOST}"
        REACT_APP_EOS_API_PORT: "${REACT_APP_EOS_API_PORT}"
        REACT_APP_EOS_API_PROTOCOL: "${REACT_APP_EOS_API_PROTOCOL}"
        REACT_APP_EOS_CHAIN_ID: "${REACT_APP_EOS_CHAIN_ID}"
        REACT_APP_HASURA_URL: "${REACT_APP_HASURA_URL}"
        REACT_APP_MAPBOX_ACCESS_TOKEN: "${REACT_APP_MAPBOX_ACCESS_TOKEN}"
        REACT_CAPTCHA_KEY: "${REACT_CAPTCHA_KEY}"
        REACT_APP_BLOCK_EXPLORER_URL: "${REACT_APP_BLOCK_EXPLORER_URL}"
    ports:
      - "3000:3000"
    depends_on:
      - hasura
  nginx:
    container_name: "${STAGE}-${APP_NAME}-nginx"
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ${NGNIX_CERTIFICATES}:/opt/application/nginx/certificates
    ports:
      - 80:80
      - 443:443